### PR TITLE
Run simplifier before generating ByteCode

### LINKED ISSUE #256: Template Haskell: ByteCodeLink.lookupCE During interactive linking, GHCi couldn't find the following symbol
The new Template Haskell support seems to get further at work, now failing with:

```
ghcide version: 0.0.5 (GHC: 8.8.1)
Ghcide setup tester in /home/ollie/work/circuithub.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/6: Finding files to test in /home/ollie/work/circuithub
Found 1 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading ./hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session

Step 5/6: Initializing the IDE

Step 6/6: Type checking the files
ghcide: ^^ Could not load 'filepickerzmpolicyzm0zi2zi6zmLUnJDYkanFc1p7RlDh5zzSr_NetworkziFilepickerziHandle_FilepickerHandle_closure', dependency unresolved. See top entry above.

File:     entities/Model/Common.hs
Range:    1:0-100001:0
Source:   typecheck
Severity: DsError
Message: 
  Program error:
  ByteCodeLink.lookupCE
  During interactive linking, GHCi couldn't find the following symbol:
  filepickerzmpolicyzm0zi2zi6zmLUnJDYkanFc1p7RlDh5zzSr_NetworkziFilepickerziHandle_FilepickerHandle_closure
  This may be due to you not asking GHCi to load extra object files,
  archives or DLLs needed by your current session. Restart GHCi, specifying
  the missing library using the -L/path/to/object/dir and -lmissinglibname
  flags, or simply by naming the relevant files on the GHCi command line.
  Alternatively, this link failure might indicate a bug in GHCi.
  If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
ghcide: ^^ Could not load 'OctopartV3ziTypesziCore_Uid_closure', dependency unresolved. See top entry above.

File:     entities/Model/OctopartV3.hs
Range:    1:0-100001:0
Source:   typecheck
Severity: DsError
Message: 
  Program error:
  ByteCodeLink.lookupCE
  During interactive linking, GHCi couldn't find the following symbol:
  OctopartV3ziTypesziCore_Uid_closure
  This may be due to you not asking GHCi to load extra object files,
  archives or DLLs needed by your current session. Restart GHCi, specifying
  the missing library using the -L/path/to/object/dir and -lmissinglibname
  flags, or simply by naming the relevant files on the GHCi command line.
  Alternatively, this link failure might indicate a bug in GHCi.
  If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
ghcide: ^^ Could not load 'filepickerzmpolicyzm0zi2zi6zmLUnJDYkanFc1p7RlDh5zzSr_NetworkziFilepickerziHandle_FilepickerHandle_closure', dependency unresolved. See top entry above.

File:     entities/Model/User.hs
Range:    1:0-100001:0
Source:   typecheck
Severity: DsError
Message: 
  Program error:
  ByteCodeLink.lookupCE
  During interactive linking, GHCi couldn't find the following symbol:
  filepickerzmpolicyzm0zi2zi6zmLUnJDYkanFc1p7RlDh5zzSr_NetworkziFilepickerziHandle_FilepickerHandle_closure
  This may be due to you not asking GHCi to load extra object files,
  archives or DLLs needed by your current session. Restart GHCi, specifying
  the missing library using the -L/path/to/object/dir and -lmissinglibname
  flags, or simply by naming the relevant files on the GHCi command line.
  Alternatively, this link failure might indicate a bug in GHCi.
  If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
Files that failed:
 * api/src/Daemon/Notification/Consignment.hs
```

My `hie.yaml` is:

```yaml
cradle:
  direct:
    arguments:
      - -Wall
      - -fno-warn-orphans
      - -hide-package resource-pool
      - -hide-package servant-checked-exceptions-core
      - -ich-aws/lib
      - -ich-eda/src
      - -ich-linear/lib
      - -ich-model/lib
      - -ich-persistence/src
      - -ich-segment/lib
      - -ich-servant-auth/lib
      - -ich-stripe/lib
      - -ich-wai-extra/lib
      - -idaemons/ch-shipment-tracking/src
      - -idaemons/ch-sync-mycronic-events/lib
      - -idaemons/ch-sync-trays/lib
      - -ieffects/hedis-simple-effects/lib
      - -ieffects/http-client-simple-effects/lib
      - -ientities
      - -iex-pool-prometheus/lib
      - -imouse-proxy/shared
      - -ioctopart
      - -ipicofactory/aoi/lib
      - -ipicofactory/coordinator/lib
      - -ipicofactory/jpctl/src
      - -ipicofactory/linescan-image-archiver/src
      - -ipicofactory/my300/src
      - -ipicofactory/panelisation/lib
      - -ipicofactory/ur10/lib
      - -ipicofactory/ur10/src-lib
      - -iprelude
      - -iquoting/lib
      - -package-env - # so that .ghci-environment.* generated by cabal is not used
```

The z-encoded name in question comes from something that is in my package database, as witnessed by:

```
$ ghc-pkg dump | grep Network.Filepicker.Handle
Network.Filepicker.Handle Network.Filepicker.Policy
```

### PR DESCRIPTION
**Pull request by mpickering**
Running the simplifier is necessary to do things like inline data
constructor wrappers.

Fixes #256 and #393

### CODE REVIEW

File: src/Development/IDE/Core/Compile.hs [hunk 1]
```diff
@@ -144,9 +145,14 @@ compileModule packageState deps tmr =
                 let pm' = pm{pm_mod_summary = tweak $ pm_mod_summary pm}
                 let tm' = tm{tm_parsed_module  = pm'}
                 GHC.dm_core_module <$> GHC.desugarModule tm'
-
+            let tc_result = fst (tm_internals_ (tmrModule tmr))
```
Comment (cocreature) [inline src/Development/IDE/Core/Compile.hs]: Do we need to set `-O0` explicitly or does `hie-bios` set that?

Comment (mpickering) [reply src/Development/IDE/Core/Compile.hs]: I was under the impression that `ghcide` set all the flags it was interested in. At least on the `.hi` files branch, I believe this is the case.

Comment (cocreature) [reply src/Development/IDE/Core/Compile.hs]: I don’t know any code that sets `-O0`. I think so far it just didn’t matter since we didn’t run the simplifier and don’t do code generation.

Comment (fendor) [reply src/Development/IDE/Core/Compile.hs]: `hie-bios` definitely sets it: https://github.com/mpickering/hie-bios/blob/master/src/HIE/Bios/Environment.hs#L41
Assuming, `ghcide` still uses `initSession`.

Comment (mpickering) [reply src/Development/IDE/Core/Compile.hs]: On the .hi file branch this will need to be set but for now, `initSession` does set it.

**Comment by mpickering** [comment]
Added a test now which I verified fails before this patch but succeeds with the patch.

**Comment by ocharles** [comment]
At long last with this branch I can almost load our main API server into `ghcide`! Only 14 files left to go (273 files now work), but that's a different bug :tada: Great work @mpickering!
