### PR TITLE
Restore Shake profiling

### LINKED ISSUE #620: --shake-profiling no longer works
Broken by #554

### PR DESCRIPTION
**Pull request by pepeiborra**
Fixes #620

### CODE REVIEW

File: src/Development/IDE/Core/Shake.hs [hunk 1]
```diff
@@ -260,15 +250,13 @@ data IdeState = IdeState
...
 -- This is debugging code that generates a series of profiles, if the Boolean is true
-shakeRunDatabaseProfile :: Maybe FilePath -> ShakeDatabase -> [Action a] -> IO ([a], Maybe FilePath)
-shakeRunDatabaseProfile mbProfileDir shakeDb acts = do
-        (time, (res,_)) <- duration $ shakeRunDatabase shakeDb acts
-        proFile <- for mbProfileDir $ \dir -> do
+shakeDatabaseProfile :: Maybe FilePath -> ShakeDatabase -> IO (Maybe FilePath)
+shakeDatabaseProfile mbProfileDir shakeDb =
+        for mbProfileDir $ \dir -> do
                 count <- modifyVar profileCounter $ \x -> let !y = x+1 in return (y,y)
-                let file = "ide-" ++ profileStartTime ++ "-" ++ takeEnd 5 ("0000" ++ show count) ++ "-" ++ showDP 2 time <.> "html"
```
Comment (ndmitchell) [inline src/Development/IDE/Core/Shake.hs:268]: I found it quite useful to find the slow database runs quickly by seeing their time in the filename. Typically there are 6 0.00s profiles and one which takes 5s.

File: src/Development/IDE/Core/Shake.hs [hunk 2]
```diff
@@ -429,7 +417,14 @@ shakeRestart it@IdeState{shakeExtras=ShakeExtras{logger}, ..} systemActs =
         shakeSession
         (\runner -> do
               (stopTime,queue) <- duration (cancelShakeSession runner)
-              logDebug logger $ T.pack $ "Restarting build session (aborting the previous one took " ++ showDuration stopTime ++ ")"
+              res <- shakeDatabaseProfile shakeProfileDir shakeDb
+              let profile = case res of
+                      Just fp ->
+                          let link = case filePathToUri' $ toNormalizedFilePath' fp of
+                                          NormalizedUri _ x -> x
+                          in ", profile saved at " <> T.unpack link
```
Comment (ndmitchell) [inline src/Development/IDE/Core/Shake.hs:425]: Why are we packing and unpacking the filepath? Why not just dump fp into the message?

File: src/Development/IDE/Core/Shake.hs (hunk 1 above)
Comment (pepeiborra) [reply src/Development/IDE/Core/Shake.hs:268]: With the Shake session there is no longer a single run being measured, the profiles measure all what happened for the duration of the session. 

In the absence of that metric, I considered tagging the profiles by the *duration* of the session, but I figured out this would be misleading.

File: src/Development/IDE/Core/Shake.hs (hunk 2 above)
Comment (pepeiborra) [reply src/Development/IDE/Core/Shake.hs:425]: This is what the code was doing previously, in an attempt to generate a clickable link. That never worked for me, so I'm happy to remove it.
